---
title: "Blé dur et sorgho - stat agricole"
author: "B. Maranget"
date: "25/01/2021"
output: 
  html_document: 
    number_sections: yes
    toc: yes
    toc_float: true
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
# Passer la valeur suivante à TRUE pour reproduire les extractions.
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

# Cadre

## Objet

Cartographie culture blé dur et sorgho. Données Agreste 2021.


## Librairies et répertoire

```{r}
library(sf)
# Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(lwgeom) # pour la validation de la géométrie
library(cartography)
```




# Données


```{r}
# communes sans la corse
dpt <- st_read("../dataE/00_ADMIN/ADMIN_EXPRESS_2021/DEPARTEMENT.shp", quiet = TRUE, stringsAsFactors = F)
fond <- st_read("../dataE/00_ADMIN/nuts.gpkg", "pays", quiet = TRUE, stringsAsFactors =F)
sorgho <- read.csv("../dataE/01_CULTURES/sorgho.csv")
bd <- read.csv("../dataE/01_CULTURES/BD.csv")
```


# Jointure

Une seule table pour toutes les données département année

```{r}
nettoyage <- function(data) {
  data$val [data$val == 0] <- NA
  # passage numérique du champ val
  data$val <- as.numeric(gsub(",",".",data$val))
  data$INSEE_DEP <- substring(data$zone, 1, 2)
  datafin <- merge(data, dpt, by = "INSEE_DEP")
  diff <- setdiff(data$INSEE_DEP, datafin$INSEE_DEP)
  return(st_as_sf(datafin))
}
sorghodpt <- nettoyage(sorgho)
summary(sorghodpt$val)
class(sorghodpt)
bddpt <- nettoyage(bd)
summary(bddpt$val)
par(mfrow = c(1,2))
par(mar = c(4,4,4,2))
barplot(sort(bddpt$val), border = "green", main = "répartition aire blé dur", xlab = "Observations")
par(mar = c(4,4,4,2))
barplot(sort(sorghodpt$val), border = "coral3", main = "répartition aire sorgho", xlab = "Observations")
```


# Carto

## Séries temporelles

```{r}
carto <- function (data, an) {
  sizes <- getFigDim(dpt, width = 800, res = 100)
  png(paste0("../img/data", an, ".png"), width = sizes [1], height = sizes [2], res = 100)
    par(mar = c(1,1,1.2,1))
  data <- data [data$an == an,]
  bks <- c(0,1,2,4,8,16)
  mypal <- carto.pal(pal1 = "wine.pal", n1 = 5)
  ghostLayer(dpt, bg = "lightblue1")
  plot(fond, border = "grey", col = "antiquewhite2", add = TRUE)
  choroLayer(data, var = "val", breaks = bks, col = mypal, legend.pos = "topright", border = "antiquewhite2", colNA = "white", legend.title.txt = "aire (milliers ha)", add = TRUE)
  layoutLayer(title = paste0("surface de sorgho - ", an), theme = "wine.pal", author = "Arvalis, 2021", source = "Eurostat / IGN / Agreste")
  dev.off()
}
for (i in 1995:2020){
  carto(sorghodpt, i)
}
```

```{r}
carto <- function (data, an) {
  sizes <- getFigDim(dpt, width = 800, res = 100, mar = c(0,0,1.2,0))
  png(paste0("../img/bd", an, ".png"), width = sizes [1], height = sizes [2], res = 100)
  par(mar = c(1,1,1.2,1))
  data <- data [data$an == an,]
  bks <- c(0,1,2,4,8,16,32,68)
  mypal <- carto.pal(pal1 = "green.pal", n1 = 7)
  ghostLayer(dpt, bg = "lightblue1")
  plot(fond, border = "grey", col = "antiquewhite2", add = TRUE)
  choroLayer(data, var = "val", breaks = bks, col = mypal, legend.pos = "topright", border = "antiquewhite2", colNA = "white", legend.title.txt = "aire (milliers ha)", add = TRUE)
  layoutLayer(title = paste0("surface de blé dur - ", an), theme = "green.pal", author = "Arvalis, 2021", source = "Eurostat / IGN / Agreste")
  dev.off()
}

for (i in 1995:2020){
  carto(bddpt, i)
}

```


## Evolutions

```{r}
evolution <- function(data, an1, an2) {
  data$val [data$val == 0] <- NA
  # passage numérique du champ val
  data$val <- as.numeric(gsub(",",".",data$val))
  data$INSEE_DEP <- substring(data$zone, 1, 2)
  data1 <- data [data$an == an1,]
  data2 <- data [data$an == an2,]
  res1 <- merge(dpt, data1, all.x = TRUE, by = "INSEE_DEP")
  res2 <- merge(res1, data2, all.xy = TRUE, by = "INSEE_DEP")
  res2$diff <- res2$val.y - res2$val.x
  summary(res2$diff)
  res2$evol <- ((res2$val.y- res2$val.x)/res2$val.y) * 100
  summary(res2$evol)
  return(res2)
}
data <- evolution(sorgho,1995,2020)
carto <- function (data) {
  an <- c(data$année.x[1], data$année.y [1])
  sizes <- getFigDim(dpt, width = 800, res = 100, mar = c(0,0,1.2,0))
  png(paste0("../img/sorgho.png"), width = sizes [1], height = sizes [2], res = 100)
  par(mar = c(1,1,1.2,1))
  bks <- c(-41,0,50,60,70,80,90,100)
  mypal <- carto.pal(pal1 = "green.pal", n1 = 1, pal2 = "wine.pal", n2 =6)
  ghostLayer(dpt, bg = "lightblue1")
  plot(fond, border = "grey", col = "antiquewhite2", add = TRUE)
  choroLayer(data, var = "evol", breaks = bks, col = mypal, legend.pos = "topright", border = "antiquewhite2", colNA = "white", legend.title.txt = paste0(an[2], " - ",an[1], " / ", an[2], " (%)"), add = TRUE)
  
  layoutLayer(title = paste0("Evolution surface de sorgho - ", an[1], " - ", an[2]), theme = "wine.pal", author = "Arvalis, 2021", source = "IGN / Agreste")
  dev.off()
}
carto(data)


data <- evolution(bd, 1995,2020)
carto <- function (data) {
  an <- c(data$année.x[1], data$année.y [1])
  sizes <- getFigDim(dpt, width = 800, res = 100, mar = c(0,0,1.2,0))
  png(paste0("../img/bd.png"), width = sizes [1], height = sizes [2], res = 100)
  par(mar = c(1,1,1.2,1))
  bks <- c(-680,-300,-100,0,30,60,90,100)
  mypal <- carto.pal(pal1 = "wine.pal", n1 = 3, pal2 = "green.pal", n2 = 4)
  ghostLayer(dpt, bg = "lightblue1")
  plot(fond, border = "grey", col = "antiquewhite2", add = TRUE)
  choroLayer(data, var = "evol", breaks = bks, col = mypal, legend.pos = "topright", border = "antiquewhite2", colNA = "white", legend.title.txt = paste0(an[2], " - ",an[1], " / ", an[2], " (%)"), add = TRUE)
  
  layoutLayer(title = paste0("Evolution surface de blé dur - ", an[1], " - ", an[2]), theme = "green.pal", author = "Arvalis, 2021", source = "IGN / Agreste")
  dev.off()
}
carto(data)
```


