---
title: "DST 2 : BNDB"
output:
  html_document:
    number_sections: yes
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval  = TRUE)
knitr::opts_chunk$set(echo  = TRUE)
knitr::opts_chunk$set(warning  = FALSE)
``` 





# Préparation de la donnée

On lit une des tables de la donnée

```{r}
data <- read.csv("data/gros/bndb/batiment_construction.csv", fileEncoding = "UTF-8")
names(data)
hist(data$hauteur)
summary(data$hauteur)
# la table comporte des valeurs élevées mais elles sont peu importantes
data <- data [data$hauteur < 500,]
categorie <- cut(data$hauteur, breaks = c(0,10,20,60,200))
df <- data.frame(data, categorie)
table(df$categorie, useNA = "always")
```

Variance : hauteur par commune

```{r}
boxplot(data$hauteur~data$code_commune_insee, las = 2)
hist(data [data$code_commune_insee == "93001","hauteur"])
```

```{r}
data$code_commune_insee <- as.factor(data$code_commune_insee)
modele <- lm(data$hauteur~data$code_commune_insee)
anova(modele)
```

```{r}
Ftable <- qf(p=.05, df1=39, df2=211000, lower.tail=FALSE)
Fcalcule <- 635
```

Rejet de l'hypothèse nulle d'indépendance. La taille des immeubles dépend de la commune.

intensité

```{r}
10000/(10000+14)
```

Etude des immeubles les plus hauts

20 étages environ = 60 m

```{r}
data <- data [data$hauteur > 60,]
boxplot(data$hauteur~ data$code_commune_insee)
```

006 048 et 055 : Bagnolet, Montreuil et Pantin


```{r}
data <- data [data$code_commune_insee %in% c("93006","93048","93055"),]

```

