---
title: "Statistiques bi variées - base"
output:
  html_document:
    number_sections: yes
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Méthode

## 5 étapes

1. Hypothèse
2. Le tableau de données
3. L'intensité
4. Les écarts au modèle
5. Explication géographique

## 3 combinaisons

### deux types de variables

1. continu
2. classe ou catégorie


### Trois méthodes

- Classe / catégorie -> Khi2

- Continu -> Régression Correlation

- Continu et classe / catégorie -> Analyse de variance


# Exemples

Utiliser le site opendata du gouvernement, choisir une thématique.

Pour chaque exemple, justifier le traitement qu'il faudra utiliser et l'hypothèse
de départ.

## exemple de l'exemple

thématique : emploi, ancienneté au chomage et niveau de formation

hypothèse : relation entre l'ancienneté au chomage et niveau de formation

thématique : santé et covid, type de lits par région

hypothèse : les différents type de lits sont cohérents entre les régions malgré
les inégalités entre région

thématique : logement et urbanisme, consommation énergétique bâtiment

hypothèse : relation entre consommation entre énergie électrique et les autres formes d'énergie



