---
title: "Préparation des données pour bases conceptuelles"
output:
  html_document:
    number_sections: yes
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval  = FALSE)
knitr::opts_chunk$set(echo  = TRUE)
knitr::opts_chunk$set(warning  = FALSE)
``` 



```{r}
library(sf)
library(mapsf)
library(mapview)
```

# Objectif

A partir des données remplies par les étudiants, on met en place le support
des story map.

A savoir :

- une carte avec les différents groupes (nom groupe, étudiant, problèmatique, données)

- une proposition de traitement par groupe à faire en cours




```{r}
library(sf)
library(mapsf)
library(mapview)
```

# code insee


```{r}
base <- st_read("data/concept.gpkg", "ville")
etudiant <- read.csv("data/td10GroupeDonnee.csv")
etudiant <- etudiant [etudiant$prénom !="",]
inseeEt <- etudiant$code.INSEE..minimum.10.bureaux.
inseeV <- base$insee
erreur <- setdiff(inseeEt, inseeV)
# bcp insee ont disparu
poubelle <- setdiff(inseeV, inseeEt)
```

les erreurs : 29232 2A004 94067 75117

```{r}
correction <- c("29232", "2A004", "94067", "75117")
df <- data.frame(erreur, correction)
df
joint <- merge(etudiant, df, by.x = "code.INSEE..minimum.10.bureaux.", by.y = "erreur", all.x=T)
joint$insee <- ifelse(is.na(joint$correction), joint$code.INSEE..minimum.10.bureaux., joint$correction )
joint [, c("insee", "prénom")]
```

# groupe et TD


```{r}
joint$groupe <- toupper(joint$nom.sexy.pour.votre.groupe..sera.utilisé.comme.titre.de.la.story.map.)
table(joint$groupe)
joint <- merge(base [, c("insee")], joint [, c("groupe", "insee", "prénom")], by = "insee") 
joint
file.remove("data/groupe.geojson")
st_write(joint , "data/groupe.geojson", append = F)
```

Les données et les problématiques

```{r}
etudiant$sources.du.données.du.cours..data.gouv..iris.résultats.des.votes.filosofi.limites.administratives.bv..lieu.et.contours..vf
etudiant$esquisse.de.votre.problématique..individuelle.
etudiant$repérer.d.autres.sources.de.données.que.celles.du.cours
```


