---
title: "Analyse script étudiant groupe 1"
output:
  html_document:
    number_sections: yes
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval  = TRUE)
knitr::opts_chunk$set(echo  = TRUE)
knitr::opts_chunk$set(warning  = FALSE)
``` 


# Objectif

11 étudiants ont déposé un script multivarié pour remplacer l'heure de cours
non effectuée lundi 27 novembre.

Le retour est personnalisé.

```{r}
library(sf)
library(mapsf)
```

# Ouverture des scripts


```{r}
fic <- list.files("data/scriptEtudiant/", recursive = T)
fic
fic <- fic[-(grep("CORRIGE|orrige", fic))]
extension <- NULL
for (f in fic){
  nb <- nchar(f)
  extension <- c(extension, substring(f, nb-1, nb))
}
table(extension)
```

4 scripts R et 7 pdf




# Points importants

## Le code postal

```{r}
data <- read.csv("data/election2022.csv", dec =",")
table(data$INSEE_COM)
data$INSEE_COM <- substring(data$Code.du.b.vote, 1,5)
table(data$INSEE_COM)
```


## Les numéros de bureau

```{r}
commune <- data [data$INSEE_COM == '01249',]
commune$Code.du.b.vote
rownames(commune) <- c(1:6)
# toujours regarder le résultat, ici sur les 4 premières colonnes
head(commune)[,1:4]
```


## Enregistrement graphique

```{r}
png("img/graphique.png")
hist(commune$Abstentions)
dev.off()
```



